version: "3.9"

services:
  vote:
    build: ./vote

  result:
    build: ./result

  worker:
    build: ./worker

  redis:
    image: redis:alpine

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
