version: "3.8"

services:
  vote:
    image: hzvonenko.azurecr.io/vote:latest
    ports:
      - "5000:80"

  result:
    image: hzvonenko.azurecr.io/result:latest
    ports:
      - "5001:80"

  worker:
    image: hzvonenko.azurecr.io/worker:latest

  redis:
    image: redis:latest

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
